# Generated by Django 5.1.4 on 2024-12-21 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('coordinate', models.CharField(max_length=256)),
                ('participant', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=16384)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_detail', to='main.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='upload/%Y/%m/%d/%H/%M/%S/')),
                ('activity_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.activitydetail')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='upload/%Y/%m/%d/%H/%M/%S/')),
                ('activity_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.activitydetail')),
            ],
        ),
    ]
