# Generated by Django 5.1.4 on 2024-12-21 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='coordinate',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(default='', max_length=16384),
        ),
        migrations.AlterField(
            model_name='activity',
            name='detail_text',
            field=models.CharField(default='', max_length=16384),
        ),
        migrations.AlterField(
            model_name='activity',
            name='detail_title',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='activity',
            name='endDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='activity',
            name='participant',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='activity',
            name='photo_path',
            field=models.CharField(default='', max_length=16384),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='activity',
            name='username',
            field=models.CharField(default='wcz', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='video_path',
            field=models.CharField(default='', max_length=16384),
        ),
    ]
