# Generated by Django 5.1.4 on 2024-12-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_activity_coordinate_alter_activity_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='username',
            field=models.CharField(default='wcz', max_length=256),
        ),
    ]
